services:
  nginx:
    image: nginx:alpine
    ports:
      - "5000:5000"
    volumes:
      - ./docker/development/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/development/nginx/auth/htpasswd:/etc/nginx/auth/htpasswd
    depends_on:
      - registry

  registry:
    image: registry:2
    volumes:
      - registry:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true

  registry-cli:
    build: ./docker/registry-cli

volumes:
  registry:
